language: generic

services:
  - docker

addons:
  apt:
    update: true
#
# go:
#   - 1.12.4

before_install:
  - sudo apt-get install -y curl jq
  - docker build . -t travistest:latest
  - docker ps -a
  - docker run -p8080:8080 --rm -d travistest:latest

script:
  - ./test.sh
